name: naod_hd_camera
description: Naod HD Camera - professional Android and iOS camera app
publish_to: "none"
version: 1.5.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.1
  gal: ^2.3.3

flutter:
  uses-material-design: true
