name: naod_hd_camera
description: Naod HD Camera
publish_to: "none"
version: 1.5.1+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.1
  gal: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/naod_logo.jpg
